### ISSUE TITLE
编译tpl文件报错

### ISSUE THREAD

**Issue by movqq** [pillys/nodetpl#2]
C:\Users\movf\AppData\Roaming\npm\node_modules\nodetpl\lib\cli.js:42
    if (!path.isAbsolute(options.path)) {
              ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at async.waterfall.fs.stat.filemode (C:\Users\movf\AppData\Roaming\npm\node_
modules\nodetpl\lib\cli.js:42:15)
    at nextTask (C:\Users\movf\AppData\Roaming\npm\node_modules\nodetpl\node_mod
ules\async\dist\async.js:6627:18)
    at Object.waterfall (C:\Users\movf\AppData\Roaming\npm\node_modules\nodetpl\
node_modules\async\dist\async.js:6630:9)
    at Object.<anonymous> (C:\Users\movf\AppData\Roaming\npm\node_modules\nodetp
l\lib\cli.js:30:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by pillys** [comment]
Node.js 是哪个版本？
可以尝试升级一下 node.js 到新版。

**Comment by movqq** [comment]
好了，升级node之后编译成功。谢谢
